language: python
python: nightly
before_install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-dev.txt
install: pip install -ve .
script: coverage run --source sqlalchemy_media $(which nosetests)
after_success: coveralls
deploy:
  provider: pypi
  user: Vahid.Mardani
  password:
    secure: lpXPW0rk6iYk0dMwP1yR59vmt7gY/7xwcQe4k9lDZuKNdyaUgKG306o37mgSoQXSXEBzrRHhIXqHXRIpNUzgnhdB93CvwCD0dK0kZZKnyfUg8qop8kJttVSSzNhjDZE6db48ir77IaYNDdJCU5n16hCuRy7HKc+UMHzI9q6sf/w=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: pylover/maryjane
    all_branches: true