language: python
python: nightly
before_install:
  - pip install -U pip setuptools wheel
  - pip install -Ur requirements-dev.txt
install: pip install -ve .
script: coverage run --source maryjane $(which nosetests)
after_success: coveralls
after_deploy: python3 setup.py bdist_wheel upload
deploy:
  provider: pypi
  user: Vahid.Mardani
  password:
    secure: lpXPW0rk6iYk0dMwP1yR59vmt7gY/7xwcQe4k9lDZuKNdyaUgKG306o37mgSoQXSXEBzrRHhIXqHXRIpNUzgnhdB93CvwCD0dK0kZZKnyfUg8qop8kJttVSSzNhjDZE6db48ir77IaYNDdJCU5n16hCuRy7HKc+UMHzI9q6sf/w=
  on:
    tags: true
    distributions: sdist
    repo: pylover/maryjane
    all_branches: true